#!/bin/bash
set -euxo pipefail

echo "🔵 build"
source hooks/.config

if [ $DOCKER_TAG != "latest" ]; then
  hath_version=$DOCKER_TAG
fi

docker buildx create --use --name mybuilder

docker buildx ls

docker build \
  --build-arg HATH_VERSION=${hath_version} \
  --platform=linux/arm,linux/arm64,linux/amd64 \
  --file $DOCKERFILE_PATH \
  --tag "${DOCKER_REPO}:${DOCKER_TAG}"  \
  .

echo "✅ images built:"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker image ls
