#!/bin/bash
set -euxo pipefail

echo "🔵 build"
source hooks/.config

if [ $DOCKER_TAG != "latest" ]; then
  hath_version=$DOCKER_TAG
fi

#docker buildx create --use --name mybuilder

#docker buildx ls
#docker buildx install
docker buildx create --use --name mybuild
docker buildx ls
docker buildx build \
  --build-arg HATH_VERSION=1.4.2 \
  --platform linux/amd64,linux/arm64/v8 \
  --file $DOCKERFILE_PATH \
  --tag "${DOCKER_REPO}:${DOCKER_TAG}" \
  .

echo "✅ images built:"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker image ls
